version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: uuid
        update-types:
          - version-update:semver-major
      - dependency-name: prisma
        update-types:
          - version-update:semver-major
      - dependency-name: "@prisma/client"
        update-types:
          - version-update:semver-major
      - dependency-name: eslint
        update-types:
          - version-update:semver-major
      - dependency-name: lucide-react
        update-types:
          - version-update:semver-major
      - dependency-name: zod
        update-types:
          - version-update:semver-major
      - dependency-name: typescript
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: actions/upload-artifact
        update-types:
          - version-update:semver-major
      - dependency-name: actions/github-script
        update-types:
          - version-update:semver-major
