export const adminNavItems = [
  { href: '/admin/dashboard', label: 'Dashboard', icon: 'layout-dashboard' },
  {
    href: '/admin/kabupaten',
    label: 'Dashboard Kabupaten',
    icon: 'landmark',
    permission: 'tenants.regency_overview',
    regencyOnly: true,
  },
  {
    href: '/admin/kecamatan',
    label: 'Dashboard Kecamatan',
    icon: 'landmark',
    permission: 'tenants.district_overview',
    districtOnly: true,
  },
  { href: '/admin/penduduk', label: 'Penduduk', icon: 'users', permission: 'population.read' },
  { href: '/admin/wilayah', label: 'Wilayah', icon: 'map-pin', permission: 'population.read' },
  { href: '/admin/peristiwa', label: 'Peristiwa Sipil', icon: 'calendar-heart', permission: 'population.read' },
  { href: '/admin/keluarga', label: 'Keluarga / KK', icon: 'home', permission: 'families.read' },
  { href: '/admin/surat', label: 'Layanan Surat', icon: 'file-text', permission: 'letters.read' },
  { href: '/admin/surat/pengaturan', label: 'Pengaturan Surat', icon: 'file-cog', permission: 'letters.manage' },
  { href: '/admin/pengaduan', label: 'Pengaduan', icon: 'message-square', permission: 'complaints.read' },
  { href: '/admin/bantuan-sosial', label: 'Bantuan Sosial', icon: 'heart-handshake', permission: 'aid.read' },
  { href: '/admin/aset', label: 'Aset Desa', icon: 'building', permission: 'assets.read' },
  { href: '/admin/pembangunan', label: 'Pembangunan', icon: 'hard-hat', permission: 'development.read' },
  { href: '/admin/keuangan', label: 'Keuangan', icon: 'wallet', permission: 'finance.read' },
  { href: '/admin/bumdes', label: 'BUMDes', icon: 'building', permission: 'bumdes.read' },
  { href: '/admin/berita', label: 'CMS Berita', icon: 'newspaper', permission: 'cms.read' },
  { href: '/admin/agenda', label: 'CMS Agenda', icon: 'calendar', permission: 'cms.read' },
  { href: '/admin/galeri', label: 'CMS Galeri', icon: 'images', permission: 'cms.read' },
  { href: '/admin/laporan', label: 'Laporan', icon: 'file-bar-chart', permission: 'reports.read' },
  { href: '/admin/users', label: 'Pengguna', icon: 'user-cog', permission: 'users.read' },
  { href: '/admin/roles', label: 'Peran & Hak Akses', icon: 'shield', permission: 'roles.read' },
  { href: '/admin/audit-logs', label: 'Audit Log', icon: 'scroll-text', permission: 'audit.read' },
  { href: '/admin/pengaturan', label: 'Pengaturan', icon: 'settings', permission: 'settings.manage' },
] as const;
